title: OS2BorgerPC produktforvaltning
description: Dokumenter, beslutninger og arbejdsgrund for produktforvaltning i OS2BorgerPC.
theme: just-the-docs

logo: "/assets/site/logo.svg"
favicon_ico: "/assets/site/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  OS2BorgerPC på OS2.eu: https://os2.eu/os2borgerpc
  OS2BorgerPC på Github: https://github.com/OS2borgerPC

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

plugins:
  - jekyll-redirect-from

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      nav_exclude: false
